//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMA.Prism.ModuleEnvoiFichePaie.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessageLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMA.Prism.ModuleEnvoiFichePaie.Resources.ErrorMessageLabels", typeof(ErrorMessageLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur n&apos;est produite : pour plus de précisions,\n consulter [{0}].
        /// </summary>
        internal static string AnErreurOccuredMsg {
            get {
                return ResourceManager.GetString("AnErreurOccuredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur durant la consolidation du dictionare..
        /// </summary>
        internal static string CantConsolidateDictionnaryMsg {
            get {
                return ResourceManager.GetString("CantConsolidateDictionnaryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier l&apos;adresse mail de l&apos;administrateur.
        /// </summary>
        internal static string CheckAdminEmailMsg {
            get {
                return ResourceManager.GetString("CheckAdminEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier le chemin du fichier [{0}].
        /// </summary>
        internal static string CheckFilePathMsg {
            get {
                return ResourceManager.GetString("CheckFilePathMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier le chemin des fichiers [{0}].
        /// </summary>
        internal static string CheckFilesPathMsg {
            get {
                return ResourceManager.GetString("CheckFilesPathMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossoble d&apos;envoyer des mails.\n Assurez-vous que l&apos;adresse : [{0}] saisie soit valide..
        /// </summary>
        internal static string ImpossibleToSendMailMsg {
            get {
                return ResourceManager.GetString("ImpossibleToSendMailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dataTable ne contient aucune donnée..
        /// </summary>
        internal static string NoDataInDataTableMsg {
            get {
                return ResourceManager.GetString("NoDataInDataTableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le repertoire selectionné n&apos;est pas valide.
        /// </summary>
        internal static string WrongDirectoryMsg {
            get {
                return ResourceManager.GetString("WrongDirectoryMsg", resourceCulture);
            }
        }
    }
}
