//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMA.Prism.ModuleEnvoiFichePaie.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModuleEnvoiFichePaieLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModuleEnvoiFichePaieLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMA.Prism.ModuleEnvoiFichePaie.Resources.ModuleEnvoiFichePaieLabels", typeof(ModuleEnvoiFichePaieLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcourir.
        /// </summary>
        internal static string BrowseLabelBtn {
            get {
                return ResourceManager.GetString("BrowseLabelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcourir.
        /// </summary>
        internal static string ChooseMailTemplateLabelBtn {
            get {
                return ResourceManager.GetString("ChooseMailTemplateLabelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer Bcc et Cc.
        /// </summary>
        internal static string ClearBccCcBoxLabelBtn {
            get {
                return ResourceManager.GetString("ClearBccCcBoxLabelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En cours d&apos;exécution ....
        /// </summary>
        internal static string ModuleLoadingLabel {
            get {
                return ResourceManager.GetString("ModuleLoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer.
        /// </summary>
        internal static string SendByMailLabelBtn {
            get {
                return ResourceManager.GetString("SendByMailLabelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prévisualiser.
        /// </summary>
        internal static string SendPreviewLabelBtn {
            get {
                return ResourceManager.GetString("SendPreviewLabelBtn", resourceCulture);
            }
        }
    }
}
